title: donatebutton.cash
email: hi@alexwinter.me
description: >-
  Easily accept online donations via Bitcoin Cash, the peer-to-peer electronic cash system.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO
lang: en
logo: /assets/images/BCH.png
social:
  name: Alex Winter
  links:
    - https://alexwinter.me
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/OG.jpg

github_url: https://github.com/sonofliberty/donatebutton.cash

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
exclude:
  - .idea
  - vendor